dist: xenial   # required for Python >= 3.7

language: python

sudo: true

python:
  - "3.7"

install:
  - pip install pipenv
  - pipenv install

script: coverage run --source=./gamebench_api_client -m unittest discover -s tests/

after_success: coveralls