dist: xenial

language: python

sudo: true

addons:
  sonarcloud:
    organization: "bigfishgames"
    token:
      secure: $SONAR_TOKEN

python:
  - "3.7"

install:
  - pip install pipenv
  - pipenv install

script:
  - coverage run --source=./gamebench_api_client -m --branch unittest discover -s tests/
  - coverage xml --include=./gamebench_api_client/*
  - sonar-scanner

deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy_scripts/main_deploy.sh $PyPi_UN $PyPi_PW $GH_TOKEN
  on:
    branch: master
