dist: xenial   # required for Python >= 3.7

language: python

sudo: true

addons:
  sonarcloud:
    organization: "bigfishgames" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN

python:
  - "3.7"

install:
  - pip install pipenv
  - pipenv install

script:
  - coverage run --source=./gamebench_api_client -m --branch unittest discover -s tests/
  - coverage xml --include=./gamebench_api_client/*
  - sonar-scanner

after_success: coveralls
